module.exports.ERROR_CODE400 = 400;
module.exports.ERROR_CODE401 = 401;
module.exports.ERROR_CODE403 = 403;
module.exports.ERROR_CODE404 = 404;
module.exports.ERROR_CODE409 = 409;
module.exports.ERROR_CODE500 = 500;
module.exports.ERROR_MESSAGE400 = 'Переданы некорректные данные';
module.exports.ERROR_MESSAGE401 = 'Ошибка авторизации';
module.exports.ERROR_MESSAGE403 = 'Нет доступа';
module.exports.ERROR_MESSAGE404 = 'Не найден запрашиваемый элемент';
module.exports.ERROR_MESSAGE409 = 'Имя или email уже заняты';
module.exports.ERROR_MESSAGE500 = 'Произошла ошибка';
module.exports.regexUrl = /https?:\/\/(www\.)?[.a-z\d-]{2,63}\.[a-z.]{2,6}(\/[\w\-.~:?#\][@!$&'()*+,;=/])*/;
module.exports.regexRU = /[^\w]+/;
module.exports.regexEN = /[^а-я^ё]+/;
